site_name: Nexus Admin Documentation
site_url: https://thenexusavenger.github.io/Nexus-Admin
repo_name: TheNexusAvenger/Nexus-Admin
repo_url: https://github.com/TheNexusAvenger/Nexus-Admin

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Creating Commands: creating-commands.md
  - API Reference:
    - Server API: api-reference/server-api.md
    - Client API: api-reference/client-api.md
    - Modules:
      - Authorization: api-reference/modules/authorization.md
      - ClientMessages: api-reference/modules/clientmessages.md
      - Configuration: api-reference/modules/configuration.md
      - Executor: api-reference/modules/executor.md
      - FeatureFlags: api-reference/modules/featureflags.md
      - Filter: api-reference/modules/filter.md
      - Gui: api-reference/modules/gui.md
      - Logs: api-reference/modules/logs.md
      - Registry: api-reference/modules/registry.md
      - Replicator: api-reference/modules/replicator.md
      - ServerMessages: api-reference/modules/servermessages.md
      - Time: api-reference/modules/time.md
      - Types: api-reference/modules/types.md
  - Frequently Asked Questions: frequently-asked-questions.md
  - Included Feature Flags: included-feature-flags.md
  - Loading: loading.md

markdown_extensions:
  - admonition
  - codehilite